[package]
name = "get-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.28"
indicatif = "0.17.8"
reqwest = "0.11.24"
tar = "0.4.40"
tokio = { version = "1.36.0", features = ["full"] }
